function X = myTriangulation(x1, x2, P1, P2)
    
    % TODO
    % x(1) means x-coordinaten, x(2) means y-coordinaten
    pre_XYZ = [x1(1)*P1(3, :)-P1(1, :); ...
               x1(2)*P1(3, :)-P1(2, :); ...
               x1(1)*P1(2, :)-x1(2)*P1(1, :); ...
               x2(1)*P2(3, :)-P2(1, :); ...
               x2(2)*P2(3, :)-P2(2, :); ...
               x2(1)*P2(2, :)-x2(2)*P2(1, :)];
     pre_XYZ_ohne_letzte_Spalte = pre_XYZ(:, 1:end-1);
     pre_XYZ_letzte_Spalte = pre_XYZ(:, end);
     X = pre_XYZ_ohne_letzte_Spalte\(pre_XYZ_letzte_Spalte*(-1)); % X := XYZ_ohne_1
     X = X';
             
end
